export function createDefaultGeneratorOverlayState() {
  return {
    enabled: false,
    hasAsset: false,
    fileName: '',
    fileSize: 0,
    fileType: '',
    objectUrl: null,
    sizePercent: 15,
    minPercent: 10,
    maxPercent: 20,
    useBadge: true,
    badgeShape: 'rounded',
    eccLevel: 'M',
    autoEcc: {
      level: 'M',
      summary: '',
      reason: '',
      risk: 'low',
      riskLabel: '標準',
      moduleSizePx: null,
      minModulePx: 3,
      meetsRisk: true,
      warnings: [],
      warningMessage: '',
    },
    lastUpdatedAt: null,
    colorProfile: {
      palette: [],
      sourceHex: '',
      backgroundHex: '#FFFFFF',
      totalSamples: 0,
      lastUpdatedAt: null,
    },
    colorMatch: {
      enabled: false,
      active: false,
      status: 'idle',
      mode: 'disabled',
      sourceHex: '',
      foregroundHex: '#0B0B0B',
      backgroundHex: '#FFFFFF',
      autoForegroundHex: '#0B0B0B',
      autoBackgroundHex: '#FFFFFF',
      manualForegroundHex: '',
      manualBackgroundHex: '',
      contrastRatio: null,
      symbolContrast: null,
      method: 'default',
      fallbackApplied: false,
      gradeLabel: '--',
      message: '',
      warnings: [],
    },
    validation: {
      quietZone: { ok: true, message: '' },
      reservedPatterns: { ok: true, message: '' },
      ecc: { ok: true, message: '' },
      format: { ok: true, message: '' },
      zxing: { status: 'idle', ok: null, message: '' },
      warnings: [],
      errors: [],
      overallOk: true,
    },
    verification: {
      lastStatus: 'idle',
      timestamp: null,
      reader: 'zxing-js',
      details: null,
    },
  };
}
